

#type Client {
#  active: Boolean
#  addresses: [ClientAddresses!]
#  emails: [ClientEmails!]
#  id: String
#  more: ClientMore
#  name: String
#  numbers: [ClientPhones!]
#}
#
#type ClientAddresses {
#  address: String
#  client: String
#  delivery: Boolean
#  id: String
#  main: Boolean
#}
#
#type ClientCompany {
#  bin: Float
#  clientMore: Float
#  id: String
#  name: String
#}
#
#type ClientEmails {
#  client: String
#  email: String
#  id: String
#  main: Boolean
#}
#
#type ClientMore {
#  client: String
#  company: ClientCompany
#  id: String
#  identifier: Float
#  labels: Label
#  notes: String
#  rate: Float
#  tags: Tag
#}
#
#type ClientPhones {
#  client: String
#  id: String
#  main: Boolean
#  phone: String
#  viber: Boolean
#  whatsapp: Boolean
#}
#
#type Label {
#  bad: Boolean
#  ban: Boolean
#  clientMore: String
#  id: String
#  supplier: Boolean
#}

type Query {
  foo: String
}
#
#type Tag {
#  charity: Boolean
#  clientMore: String
#  good: Boolean
#  id: String
#  insolvent: Boolean
#  jurface: Boolean
#  rich: Boolean
#}
